enum IndianState {
  Andhra_Pradesh,
  Arunachal_Pradesh,
  Assam,
  Bihar,
  Chhattisgarh,
  Goa,
  Gujarat,
  Haryana,
  Himachal_Pradesh,
  Jharkand,
  Karnataka,
  Kerala,
  Madhya_Pradesh,
  Maharashtra,
  Manipur,
  Meghalaya,
  Mizoram,
  Nagaland,
  Odisha,
  Punjab,
  Rajasthan,
  Sikkim,
  Tamil_Nadu,
  Telangana,
  Tripura,
  Uttar_Pradesh,
  Uttarakhand,
  West_Bengal,
  Andaman_And_Nicobar_Islands,
  Chandigarh,
  Dadra_and_Nagar_Haveli,
  Daman_and_Diu,
  Delhi,
  Jammu_and_Kashmir,
  Ladakh,
  Lakshadweep,
  Puducherry,
}

List<String> userType = ["Gym Owner","Fitness Trainer"];
List<String> gymType = ["Male","Female","Unisex"];
List<String> gender = ["Male","Female"];